### ISSUE TITLE
Prometheus - Opensource Monitoring Framework

### ISSUE THREAD

**Issue by codeanit** [codeanit/til#246]
> Resources:
- https://prometheus.io/docs/introduction/overview
- https://dzone.com/articles/go-microservices-part-15-monitoring-with-prometheu
- https://godoc.org/github.com/go-kit/kit/metrics
- https://blog.alexellis.io/prometheus-monitoring

**Comment by codeanit** [comment]
# Tasks : Learning Prometheus In Chapters

- [ ] Chapter 1. Course Introduction
- [ ] Chapter 2. Introduction to Systems and Service Monitoring
- [ ] Chapter 3. Introduction to Prometheus
- [ ] Chapter 4. Installing and Setting Up Prometheus
- [ ] Chapter 5. Basic Querying
- [ ] Chapter 6. Dashboarding
- [ ] Chapter 7. Monitoring Host Metrics
- [ ] Chapter 8. Monitoring Container Metrics
- [ ] Chapter 9. Instrumenting Code
- [ ] Chapter 10. Building Exporters
- [ ] Chapter 11. Advanced Querying
- [ ] Chapter 12. Relabeling
- [ ] Chapter 13. Service Discovery
- [ ] Chapter 14. Blackbox Monitoring
- [ ] Chapter 15. Pushing Data
- [ ] Chapter 16. Alerting
- [ ] Chapter 17. Making Prometheus Highly Available
- [ ] Chapter 18. Recording Rules
- [ ] Chapter 19. Scaling Prometheus Deployments
- [ ] Chapter 20. Prometheus and Kubernetes
- [ ] Chapter 21. Local Storage
- [ ] Chapter 22. Remote Storage Integrations
- [ ] Chapter 23. Transitioning From and Integrating with Other Monitoring Systems
- [ ] Chapter 24. Monitoring and Debugging Prometheus
