### ISSUE TITLE
Database Storage Engine

### ISSUE THREAD

**Issue by codeanit** [codeanit/til#447]
# Database Storage Engine
![image](https://user-images.githubusercontent.com/414141/105632471-5a113e80-5e7b-11eb-9307-a0864da3239a.png)

"A database engine (or storage engine) is the underlying software component that a database management system (DBMS) uses to create, read, update and delete (CRUD) data from a database. Most database management systems include their own application programming interface (API) that allows the user to interact with their underlying engine without going through the user interface of the DBMS.

The term "database engine" is frequently used interchangeably with "database server" or "database management system". A 'database instance' refers to the processes and memory structures of the running database engine." [Wikipedia](https://en.wikipedia.org/wiki/Database_engine)

"CRUD is meant to define the characteristics necessary for a database as it relates to persistent storage. It is not meant to describe everything that could be done by a database engine.

To make a comparison, fundamentally a vehicle is a device used for transport. While true, this definition certainly doesn't include all the detail entailed in a modern automobile.

A database engine might handle multiple users, transactions, MVCC (Multiversion Concurrency Control), buffers and caches, ACID (atomicity, consistency, isolation, durability), as well as different isolation levels. A read may pull data from memory, remote databases, and multiple tables on disk processing it using SQL through multiple explicit and/or implicit code paths in order to present it to the requesting application. A create may allocate storage, provision structures, assign values, and do it's own processing before storing data. Etc."

"Some databases can run many engines, depending on the best fit for the job. For example, many of my applications use InnoDB for most data (key constraints and row level locking), MyISAM for session data (fast, less processing) and ArchiveDB for audit trail (compressed and insert/select only, no update/delete).

The "rest" of the database software provides a common interface for use through APIs or terminals, allows complex actions (like joins, subqueries, etc.) and manages the health/status and configuration of the included engines. There is a lot to the feeding and care of an engine, and the database software hides all of that complexity."
-- [Stackoverflow](https://stackoverflow.com/questions/34985464/difference-between-a-database-a-storage-engine) 

"Multiversion Concurrency Control (MCC or MVCC), is a concurrency control method commonly used by database management systems to provide concurrent access to the database and in programming languages to implement transactional memory. Without concurrency control, if someone is reading from a database at the same time as someone else is writing to it, it is possible that the reader will see a half-written or inconsistent piece of data. " - [Wikipedia](https://en.wikipedia.org/wiki/Multiversion_concurrency_control)

"In a database management system, a transaction is a single unit of logic or work, sometimes made up of multiple operations."[Wikipedia](https://en.wikipedia.org/wiki/Database_transaction)

"When evaluating operational databases, developers building distributed cloud apps tend to focus on data modeling flexibility, consistency guarantees, linear scalability, fault tolerance, low latency, high throughput and easy manageability as high priority concerns. However, it is essential to have a good understanding of the underlying storage engine to reason about how the database actually delivers on these core promises. This post aims to help busy developers make informed choices in the context of database storage engines.
While there have many types of database storage engines since the early 1970s, only two of them are popular enough to merit a discussion in the context of modern distributed cloud applications — B-Tree Based and LSM Tree Based.

A B-tree is a self-balancing tree data structure that keeps data sorted and allows searches, sequential access, insertions, and deletions in logarithmic time. Pros: High throughput, low latency reads. Cons: Poor write performance. Mostly used in SQL databases.

As data volumes grew in the mid 2000s, it became necessary to write larger datasets to databases. B-Tree engines fell out of favor given their poor write performance. Database designers turned to a new data structure called Log Structured Merge (LSM) Tree Based Engine (or LSM tree). Default in popular NoSQL databases including Apache Cassandra, Elasticsearch (Lucene), Google Bigtable, Apache HBase, and InfluxDB.

" - [Yugabyte](https://medium.com/yugabyte/a-busy-developers-guide-to-database-storage-engines-the-basics-6ce0a3841e59)

# TODO
- [ ] https://en.wikipedia.org/wiki/Database_engine
- [ ] https://blog.yugabyte.com/a-busy-developers-guide-to-database-storage-engines-advanced-topics 
- [ ] https://en.wikibooks.org/wiki/Design_of_Main_Memory_Database_System/Storage_Engine
- [ ] https://dzone.com/articles/state-storage-engine
- [ ] https://blog.medium.com/what-are-bloom-filters-1ec2a50c68ff
- [ ] https://en.wikipedia.org/wiki/Comparison_of_MySQL_database_engines
