### ISSUE TITLE
Linux Device Driver

### ISSUE THREAD

**Issue by codeanit** [codeanit/til#526]
# Linux Device Driver

A driver is a is a bit of code that runs in 
the kernel to talk to some hardware device
having to know any details of how the hardware 
works.

A device driver is Linux kernel module that
is designed for a specific piece of hardware. 

Alternative to modules would be to build the 
code for each and every driver into the kernel. 
We don’t need to keep rebuilding the kernel 
every time we add a new device or if we upgrade 
an old device. This saves time and also helps in 
keeping our base kernel error-free.

Kernel modules (or loadable kernel modules) are 
pieces of code that can be loaded and unloaded 
into the kernel upon demand. They extend the 
functionality of the kernel without the need to 
reboot the system. 

# TODO
https://embetronicx.com/linux-device-driver-tutorials 
- [ ] Device Driver 1 - Introduction
- [ ] Device Driver 2 - First Driver
- [ ] Device Driver 3 - Passing Arguments
- [ ] Device Driver 4 - Major &amp; Minor Number
- [ ] Device Driver 5 - Creating Device File
- [ ] Device Driver 6 - File Operations
- [ ] Device Driver 7 - Real Device Driver
- [ ] Device Driver 8 - IOCTL Tutorial
- [ ] Device Driver 9 - Procfs Tutorial
- [ ] Device Driver 10 - Waitqueue Tutorial
- [ ] Device Driver 11 - SysFS Tutorial
